In [2]:
import numpy as np
import scipy.linalg as la

In [3]:
A = np.array([[4,8,4,0],[1,5,4,-3],[1,4,7,2],[1,3,0,-2]]);
A

array([[ 4,  8,  4,  0],
       [ 1,  5,  4, -3],
       [ 1,  4,  7,  2],
       [ 1,  3,  0, -2]])

In [4]:
P , L , U = la.lu(A)

In [6]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.25      ,  1.        ,  0.        ,  0.        ],
       [ 0.25      ,  0.66666667,  1.        ,  0.        ],
       [ 0.25      ,  0.33333333, -0.5       ,  1.        ]])

In [7]:
U

array([[ 4.,  8.,  4.,  0.],
       [ 0.,  3.,  3., -3.],
       [ 0.,  0.,  4.,  4.],
       [ 0.,  0.,  0.,  1.]])

In [10]:
D = np.diag(np.diag(U))
D

array([[4., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 1.]])

In [13]:
lower = L.dot(D)
lower

array([[ 4.,  0.,  0.,  0.],
       [ 1.,  3.,  0.,  0.],
       [ 1.,  2.,  4.,  0.],
       [ 1.,  1., -2.,  1.]])

In [15]:
upper = U
upper /= np.diag(U)[:, None]
upper

array([[ 1.,  2.,  1.,  0.],
       [ 0.,  1.,  1., -1.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
b = [28 , 13 , 23 , 4]

In [21]:
y = (la.inv(lower)).dot(b) 
y

array([7., 2., 3., 1.])

In [24]:
x = (la.inv(upper)).dot(y)
x

array([3., 1., 2., 1.])

In [26]:
ans = la.solve(A,b)
ans

array([3., 1., 2., 1.])